### ISSUE TITLE
Hide Enrichment Curves with a p-Value>0.05

### ISSUE THREAD

**Issue by keckelt** [Caleydo/touring#3]
As those curves are unimportant, they should be removed from the cart to reduce clutter.

**Comment by mstreit** [comment]
still valid?

**Comment by PatrickAdelberger** [comment]
not yet implemented, i will do that today

**Comment by PatrickAdelberger** [comment]
if there are no curves lower with a p-value lower than 0.05, then the curve with the lowest p-value available will be displayed
