### ISSUE TITLE
Axis label not in scientific format

### ISSUE THREAD

**Issue by keckelt** [Caleydo/touring#4]
Axis labels should display full numbers, i.e. 20000 instead of 2e+4

**Comment by mstreit** [comment]
@PatrickAdelberger, is this issue still valid?

**Comment by PatrickAdelberger** [comment]
@mstreit, I changed the formating so that values of 1000 and above are displayed in the e+ notation

**Comment by mstreit** [comment]
sounds good. so this issue can be closed. please also look through the other open issues and update their status. thanks.
