### ISSUE TITLE
create a worker pool

### ISSUE THREAD

**Issue by keckelt** [Caleydo/touring#6]
I think it might be better to limit the number of workers. E.g. the number of logical cores:  https://developer.mozilla.org/en-US/docs/Web/API/NavigatorConcurrentHardware/hardwareConcurrency

Chrome Kills the tab if WE spawn to many Tabs and it might become faster.

**Comment by keckelt** [comment]
E.g. Stratification by Tumor Type and comparing those stratification groups pairwise exceeds some thread limit set by chrome

**Comment by mstreit** [comment]
this issue has been solved in the meantime, right?
